version: "3.5"
services:

  # redis:
  #   image: "redis:6.0.5-alpine"
  #   command: redis-server
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis/redis-data:/var/lib/redis
  #     - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  #   environment:
  #     - REDIS_REPLICATION_MODE=master
  #   networks: 
  #       - network_test_bed

  worker-0000:
    build: ./worker_files/
    volumes: 
      - ./worker_files/:/usr/src/app:z
      - ./common/utils/:/usr/src/app/utils:z
      - ./common/base_stream/:/usr/src/app/base_stream:z
    ports:
      - "6000:6000"
    environment: 
      - PYTHONUNBUFFERED=1
      - WORKER_ID=0000
      - PORT=6000
    # depends_on: 
    #   - redis
    env_file:
      - hosts.env
      - constants.env
    networks: 
      - network_test_bed

  worker-0001:
    build: ./worker_files/
    volumes: 
      - ./worker_files/:/usr/src/app:z
      - ./common/utils/:/usr/src/app/utils:z
      - ./common/base_stream/:/usr/src/app/base_stream:z
    ports:
      - "6001:6001"
    environment: 
      - PYTHONUNBUFFERED=1
      - WORKER_ID=0001
      - PORT=6001
    # depends_on: 
    #   - redis
    env_file:
      - hosts.env
      - constants.env
    networks: 
      - network_test_bed

  worker-0002:
    build: ./worker_files/
    volumes: 
      - ./worker_files/:/usr/src/app:z
      - ./common/utils/:/usr/src/app/utils:z
      - ./common/base_stream/:/usr/src/app/base_stream:z
    ports:
      - "6002:6002"
    environment: 
      - PYTHONUNBUFFERED=1
      - WORKER_ID=0002
      - PORT=6002
    # depends_on: 
    #   - redis
    env_file:
      - hosts.env
      - constants.env
    networks: 
      - network_test_bed

networks:
  network_test_bed:
    name: network_test_bed
    external: true
