version: "3.5"
services:

  worker-0003:
    build: ./rsu_worker/
    volumes: 
      - ./rsu_worker/:/usr/src/app:z
      - ./common/utils/:/usr/src/app/utils:z
      - ./common/base_stream/:/usr/src/app/base_stream:z
    ports:
      - "6003:6003"
      - "6013:6013"
    environment: 
      - PYTHONUNBUFFERED=1
      - WORKER_ID=0003
      - PORT=6003
      - PUB_PORT=6013
      - SERVICE='OTHER'
      - X=1
      - Y=1
    env_file:
      - hosts.env
      - constants.env
    networks: 
      - network_test_bed
    restart: always
    command:
      - 'python3'
      - '-u'
      - '/usr/src/app/worker.py'

  worker-0004:
    build: ./rsu_worker/
    volumes: 
      - ./rsu_worker/:/usr/src/app:z
      - ./common/utils/:/usr/src/app/utils:z
      - ./common/base_stream/:/usr/src/app/base_stream:z
    ports:
      - "6004:6004"
      - "6014:6014"
    environment: 
      - PYTHONUNBUFFERED=1
      - WORKER_ID=0004
      - PORT=6004
      - PUB_PORT=6014
      - SERVICE='OTHER'
      - X=1
      - Y=1
    env_file:
      - hosts.env
      - constants.env
    networks: 
      - network_test_bed
    restart: always
    command:
      - 'python3'
      - '-u'
      - '/usr/src/app/worker.py'

  worker-0005:
    build: ./rsu_worker/
    volumes: 
      - ./rsu_worker/:/usr/src/app:z
      - ./common/utils/:/usr/src/app/utils:z
      - ./common/base_stream/:/usr/src/app/base_stream:z
    ports:
      - "6005:6005"
      - "6015:6015"
    environment: 
      - PYTHONUNBUFFERED=1
      - WORKER_ID=0005
      - PORT=6005
      - PUB_PORT=6015
      - SERVICE='OTHER'
      - X=1
      - Y=1
    env_file:
      - hosts.env
      - constants.env
    networks: 
      - network_test_bed
    restart: always
    command:
      - 'python3'
      - '-u'
      - '/usr/src/app/worker.py'

  worker-0006:
    build: ./rsu_worker/
    volumes: 
      - ./rsu_worker/:/usr/src/app:z
      - ./common/utils/:/usr/src/app/utils:z
      - ./common/base_stream/:/usr/src/app/base_stream:z
    ports:
      - "6006:6006"
      - "6016:6016"
    environment: 
      - PYTHONUNBUFFERED=1
      - WORKER_ID=0006
      - PORT=6006
      - PUB_PORT=6016
      - SERVICE='OTHER'
      - X=1
      - Y=1
    env_file:
      - hosts.env
      - constants.env
    networks: 
      - network_test_bed
    restart: always
    command:
      - 'python3'
      - '-u'
      - '/usr/src/app/worker.py'

  worker-0007:
    build: ./rsu_worker/
    volumes: 
      - ./rsu_worker/:/usr/src/app:z
      - ./common/utils/:/usr/src/app/utils:z
      - ./common/base_stream/:/usr/src/app/base_stream:z
    ports:
      - "6007:6007"
      - "6017:6017"
    environment: 
      - PYTHONUNBUFFERED=1
      - WORKER_ID=0007
      - PORT=6007
      - PUB_PORT=6017
      - SERVICE='OTHER'
      - X=1
      - Y=1
    env_file:
      - hosts.env
      - constants.env
    networks: 
      - network_test_bed
    restart: always
    command:
      - 'python3'
      - '-u'
      - '/usr/src/app/worker.py'

networks:
  network_test_bed:
    name: network_test_bed
    external: true
