import uuid
from .Task import Task

class Query(object):
    def __init__(self, client, json_str, socket=None):
        self._id = str(uuid.uuid4())
        self._client = client
        self._json_str = json_str
        self._socket = socket

        # For counting the tasks generated by this query
        self._generated_task_ids = []

        self._payload = []

        # An array of tasks under this query
        self._tasks = []

    def add_task_id(self, task_id):
        self._generated_task_ids.append(task_id)

    def remove_task_id(self, task_id):
        self._generated_task_ids.remove(task_id)

    def add_task(self, task):
        self._tasks.append(task)

    def remove_task(self, task):
        self._tasks.remove(task)

    def task_id_count(self):
        return len(self._generated_task_ids)

    def __str__(self):
        # return str(self._generated_task_ids)
        task_ids = ''
        # task_ids += ["{}:{}\n".format(i, t) for i, t in enumerate(self._generated_task_ids)]
        for i, t in enumerate(self._generated_task_ids):
            task_ids += "\t{}:{}\n".format(i + 1, t)
        return "Q_id: {} \n{}".format(self._id, task_ids)